### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by ktwrd** [melkortf/tf2-servers#126]
`tf2-base` image seems to be outdated and I can't find out a way to update the game. The version reported is `8568259` but the latest version for TF2DS is `8596679`.

This is my `docker-compose.yml` file
```yml
version: '3.6'

services:
  tf2:
    restart: always
    image: ghcr.io/melkortf/tf2-base
    volumes:
      - ./addons:/home/tf2/server/tf/addons
      - ./maps:/home/tf2/server/tf/maps
      - ./cfg:/home/tf2/server/tf/cfg
    ports:
      - "0.0.0.0:27015:27015/tcp"
      - "0.0.0.0:27015:27015/udp"
      - "0.0.0.0:27020:27020/tcp"
      - "0.0.0.0:27020:27020/udp"
    environment:
      - "RCON_PASSWORD=XXXXXXXX"
```
